#### Find all Doors

In [1]:
# Schritt 1: Ben√∂tigte Pakete importieren
import fitz  # PyMuPDF
import re
import pandas as pd

# Schritt 2: PDF-Dateipfad angeben (anpassen falls n√∂tig)
pdf_path = "Grundriss_Haus_1.pdf"  # Achte darauf, dass das PDF im selben Verzeichnis liegt

# Schritt 3: PDF √∂ffnen und Text extrahieren
doc = fitz.open(pdf_path)
all_text = ""
for page in doc:
    all_text += page.get_text()

# Schritt 4: T√ºr-IDs mit RegEx finden (UG, EG, OG)
pattern = r"\bT\.H1\.(UG|EG|OG)\.\d{2}\b"
door_ids = sorted(set(re.findall(pattern.replace("(UG|EG|OG)", "(?:UG|EG|OG)"), all_text)))

# Schritt 5: In DataFrame √ºberf√ºhren und aufteilen
df = pd.DataFrame(door_ids, columns=["Tuer_ID"])
df[["Typ", "Haus", "Geschoss", "Nummer"]] = df["Tuer_ID"].str.split(".", expand=True)

# Schritt 6: Ergebnis anzeigen
df.style.set_caption("üóÇÔ∏è Ausgelesene T√ºren aus dem PDF")

In [2]:
df

       Tuer_ID Typ Haus Geschoss Nummer
0   T.H1.EG.01   T   H1       EG     01
1   T.H1.EG.02   T   H1       EG     02
2   T.H1.EG.03   T   H1       EG     03
3   T.H1.EG.04   T   H1       EG     04
4   T.H1.EG.05   T   H1       EG     05
5   T.H1.EG.06   T   H1       EG     06
6   T.H1.EG.07   T   H1       EG     07
7   T.H1.EG.08   T   H1       EG     08
8   T.H1.OG.01   T   H1       OG     01
9   T.H1.OG.02   T   H1       OG     02
10  T.H1.OG.03   T   H1       OG     03
11  T.H1.OG.04   T   H1       OG     04
12  T.H1.OG.05   T   H1       OG     05
13  T.H1.OG.06   T   H1       OG     06
14  T.H1.OG.07   T   H1       OG     07
15  T.H1.UG.01   T   H1       UG     01
16  T.H1.UG.02   T   H1       UG     02
17  T.H1.UG.03   T   H1       UG     03
18  T.H1.UG.04   T   H1       UG     04
19  T.H1.UG.05   T   H1       UG     05
20  T.H1.UG.06   T   H1       UG     06
21  T.H1.UG.07   T   H1       UG     07
22  T.H1.UG.08   T   H1       UG     08
23  T.H1.UG.09   T   H1       UG     09
24  T.H1.UG.10   T   H1       UG     10
25  T.H1.UG.11   T   H1       UG     11